export const agentTopics = [
  'AI Agents',
  'LLM Infrastructure',
  'RAG Systems',
  'Prompt Engineering',
  'Automation',
  'Orchestration',
  'Next.js',
  'Web Architecture',
  'APIs',
  'Databases',
  'PostgreSQL',
  'Performance',
  'Reliability',
  'Cloud Infrastructure',
  'Developer Experience',
  'Data Pipelines',
  'ETL',
  'Business Intelligence',
  'Analytics',
  'Dashboards',
  'Operational Systems',
  'UI/UX',
  'Brand Identity',
  'Design Systems',
  'Conversion Design',
  'Motion Design',
  'Founder Execution',
  'One Person Business',
  'Productivity Systems',
  'Growth Systems',
  'Market Validation',
  'Distribution',
  'Content Systems',
  'SEO',
  'AI Search',
  'Product Strategy',
  'SaaS',
  'Digital Products',
  'SME Technology',
  'Enterprise Technology',
  'Case Studies',
  'Build in Public',
  'Experiments',
  'Lessons Learned',
  'Emerging Technology',
  'Market Opportunities',
  'Business Models',
  'Brand Positioning',
  'Creative Strategy',
  'Technical Strategy',
];
