export const agentCategories = [
  'Technical Education',
  'AI Infrastructure',
  'Engineering Breakdown',
  'Data Operations',
  'Brand Strategy',
  'Design Systems',
  'Founder Systems',
  'Build in Public',
  'Case Study',
  'Market Intelligence',
  'Product Insight',
  'Workflow Automation',
  'Opinion',
  'Framework',
  'Tutorial',
  'Explainer',
  'Behind The Scenes',
  'Announcement',
  'Offer',
  'Proof',
  'FAQ',
  'Trend',
  'Research',
  'Comparison',
  'Checklist',
  'Lesson Learned',
  'Experiment',
  'Launch',
  'Update',
  'Community Prompt',
];
